"""报告生成使用的 Markdown 格式化与转换工具。"""

import re
from typing import Dict, List, Optional


def format_report(task: str, report_content: str, sources: Optional[List[Dict[str, str]]] = None) -> str:
    """把报告内容整理成完整 Markdown 结构。

    统一标题、列表、代码块和引用来源等格式。

    参数：
        task: 原始研究任务或问题。
        report_content: 原始报告正文。
        sources: 可选来源列表，每项包含 'url' 和 'title'。

    返回：
        格式化后的 Markdown 报告字符串。
    """
    lines: List[str] = []
    lines.append(f"# Research Report: {task}")
    lines.append("")

    # 添加报告元信息。
    lines.append("> **Generated by DeepResearch-Agent**")
    lines.append("")
    lines.append("---")
    lines.append("")

    # 清理并规范化正文内容。
    cleaned = _normalize_content(report_content)

    # 如果正文没有标题，则补一个默认摘要标题。
    if not cleaned.startswith("##") and not cleaned.startswith("#"):
        cleaned = "## Abstract\n\n" + cleaned

    lines.append(cleaned)

    # 追加来源引用章节。
    if sources:
        lines.append("")
        lines.append("---")
        lines.append("")
        lines.append("## References")
        lines.append("")
        for i, src in enumerate(sources, 1):
            title = src.get("title", src.get("url", f"Source {i}"))
            url = src.get("url", "")
            if url:
                lines.append(f"{i}. [{title}]({url})")
            else:
                lines.append(f"{i}. {title}")

    return "\n".join(lines).strip()


def extract_sources_from_report(report: str) -> List[str]:
    """从报告中提取引用 URL 或来源。

    支持 Markdown 链接、裸 URL 和编号引用等常见格式。

    参数：
        report: Markdown 报告文本。

    返回：
        提取出的 URL 字符串列表。
    """
    sources: List[str] = []
    seen: set = set()

    # 模式 1：Markdown 链接 [text](url)。
    md_links = re.findall(r"\[([^\]]+)\]\(([^)]+)\)", report)
    for text, url in md_links:
        url = url.strip()
        if url and url not in seen:
            seen.add(url)
            sources.append(url)

    # 模式 2：裸 URL（http/https）。
    bare_urls = re.findall(
        r"(?<!\]\()\bhttps?://[^\s\)\]\"'>]+", report
    )
    for url in bare_urls:
        url = url.rstrip(".,;:!?")
        if url and url not in seen:
            seen.add(url)
            sources.append(url)

    return sources


def report_to_html(report: str) -> str:
    """把 Markdown 报告转换为 HTML，不依赖额外库。

    支持标题、加粗、斜体、列表、链接、代码块、引用、行内代码和段落。

    参数：
        report: Markdown 报告文本。

    返回：
        HTML 字符串。
    """
    html_parts: List[str] = []
    in_code_block = False
    code_buffer: List[str] = []
    in_list = False
    in_ordered_list = False

    lines = report.split("\n")

    for i, line in enumerate(lines):
        # 代码块处理。
        if line.strip().startswith("```"):
            if in_code_block:
                # 关闭代码块。
                newline = '\n'
                html_parts.append(f"<pre><code>{_escape_html(newline.join(code_buffer))}</code></pre>")
                code_buffer = []
                in_code_block = False
            else:
                in_code_block = True
            continue

        if in_code_block:
            code_buffer.append(line)
            continue

        # 必要时关闭未结束的列表。
        if in_list and not line.startswith("- ") and not line.startswith("* ") and not line.strip() == "":
            html_parts.append("</ul>")
            in_list = False
        if in_ordered_list and not re.match(r"^\d+\.\s", line) and not line.strip() == "":
            html_parts.append("</ol>")
            in_ordered_list = False

        # 空行。
        if line.strip() == "":
            if not in_list and not in_ordered_list:
                html_parts.append("")
            continue

        # 标题。
        heading_match = re.match(r"^(#{1,6})\s+(.+)$", line)
        if heading_match:
            level = len(heading_match.group(1))
            text = heading_match.group(2)
            html_parts.append(f"<h{level}>{_process_inline(text)}</h{level}>")
            continue

        # 分隔线。
        if line.strip() == "---":
            html_parts.append("<hr>")
            continue

        # 引用块。
        if line.startswith(">"):
            text = line.lstrip(">").strip()
            html_parts.append(f"<blockquote>{_process_inline(text)}</blockquote>")
            continue

        # 无序列表。
        list_match = re.match(r"^[\-\*]\s+(.+)$", line)
        if list_match:
            if not in_list:
                html_parts.append("<ul>")
                in_list = True
            html_parts.append(f"<li>{_process_inline(list_match.group(1))}</li>")
            continue

        # 有序列表。
        ol_match = re.match(r"^(\d+)\.\s+(.+)$", line)
        if ol_match:
            if not in_ordered_list:
                html_parts.append("<ol>")
                in_ordered_list = True
            html_parts.append(f"<li>{_process_inline(ol_match.group(2))}</li>")
            continue

        # 普通段落。
        html_parts.append(f"<p>{_process_inline(line)}</p>")

    # 关闭所有仍处于打开状态的标签。
    if in_code_block:
        newline = '\n'
        html_parts.append(f"<pre><code>{_escape_html(newline.join(code_buffer))}</code></pre>")
    if in_list:
        html_parts.append("</ul>")
    if in_ordered_list:
        html_parts.append("</ol>")

    return "\n".join(html_parts)


def _process_inline(text: str) -> str:
    """处理单行文本中的行内 Markdown 元素。

    支持加粗、斜体、行内代码和链接。
    """
    # 加粗：**text**
    text = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", text)
    # 斜体：*text*
    text = re.sub(r"(?<!\*)\*(?!\*)(.+?)(?<!\*)\*(?!\*)", r"<em>\1</em>", text)
    # 行内代码。
    text = re.sub(r"`(.+?)`", lambda m: f"<code>{_escape_html(m.group(1))}</code>", text)
    # 链接：[text](url)。
    text = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", r'<a href="\2">\1</a>', text)

    return text


def _escape_html(text: str) -> str:
    """转义 HTML 特殊字符。"""
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def _normalize_content(content: str) -> str:
    """规范化报告内容：统一换行并清理过多空行。"""
    # 统一换行符。
    content = content.replace("\r\n", "\n").replace("\r", "\n")

    # 移除连续超过 2 个的空行。
    while "\n\n\n" in content:
        content = content.replace("\n\n\n", "\n\n")

    return content.strip()


def _extract_heading(text: str, level: int = 1) -> Optional[str]:
    """提取指定级别的第一个标题。"""
    pattern = r"^" + "#" * level + r"\s+(.+)$"
    match = re.search(pattern, text, re.MULTILINE)
    if match:
        return match.group(1).strip()
    return None
